typography_spectrum: 0.9468766222707927
color:
  brandStrength: 0.23440990783274174
  lightness: 0.5919951810501516
  saturation: 0.4635335807688534
  rhythmicContrast: 0.635697107296437
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
layout_spectrum: 0.6841345543507487
author:
  name: Frances Banks
  email: frances@soulfeltdevotions.com
  url: www.soulfeltdevotions.com
name: SOULFELT HEALING
title: Take care of your sacred self
description: tips and ideas to nurture your sacred practices and self care
