typography_spectrum: 0.8979009441100061
color:
  brandStrength: 0.1414987132884562
  lightness: 0.39739017514511943
  saturation: 0.8840497727505863
  rhythmicContrast: 0.5030837971717119
  brandColors:
    - '#13101E'
    - '#5A2A55'
    - '#6B4B33'
    - '#68684D'
    - '#215255'
layout_spectrum: 0.7907887988258153
author:
  name: Frances Banks
  email: frances@soulfeltdevotions.com
  url: www.soulfeltdevotions.com
name: SOULFELT HEALING
title: Take care of your sacred self
description: tips and ideas to nurture your sacred practices and self care
